// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjEurOzywy9liqnwyXQtEc_abiZM05AUA',
    appId: '1:438810627907:web:3e28b89bf008a0aa03e9f6',
    messagingSenderId: '438810627907',
    projectId: 'responsivechatapp',
    authDomain: 'responsivechatapp.firebaseapp.com',
    storageBucket: 'responsivechatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDps1YgKxny3pBEH-fr4kKTv2tMFcBUb0o',
    appId: '1:438810627907:android:debfba2174abed1303e9f6',
    messagingSenderId: '438810627907',
    projectId: 'responsivechatapp',
    storageBucket: 'responsivechatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonHSR4QBLCr5tf-zgcprH7pFguMpqI3Q',
    appId: '1:438810627907:ios:10a07c8c9ea9ed7b03e9f6',
    messagingSenderId: '438810627907',
    projectId: 'responsivechatapp',
    storageBucket: 'responsivechatapp.appspot.com',
    iosBundleId: 'com.example.responsiveChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBonHSR4QBLCr5tf-zgcprH7pFguMpqI3Q',
    appId: '1:438810627907:ios:34020c77f4396aa303e9f6',
    messagingSenderId: '438810627907',
    projectId: 'responsivechatapp',
    storageBucket: 'responsivechatapp.appspot.com',
    iosBundleId: 'com.example.responsiveChatApp.RunnerTests',
  );
}
